name: Deploy Aventura Check to Azure

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_BFDE9302713D40A1A32903854C462C27 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_D7A7054C79A641B8952AAFFF06C0AF41 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_EF91F8C292074F7BABF1DD9854FB28FC }}

      - name: Deploy Aventura Check
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'Aventura-Check'
          slot-name: 'Production'
          package: .
